# Site settings
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.michaeljbannister.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
encoding: UTF-8

kramdown:
  input: GFM
  syntax_highlighter: rouge
  # syntax_highlighter_opts:
    #inline_theme: github # Inlines the syntax colors
    #css_class: null
  hard_wrap: false

# Collections
collections:
  research:
    output: true
  teaching:
    output: true

# Trick to use newlines in Liquid Templates
newline: "\n"

sass:
  style: compressed

# About me!
name: Michael J. Bannister
title: Assistant Professor
department: Department of Mathematics and Computer Science
school: Santa Clara University
img: assets/img/me-200x300.jpg

contacts:
    - name: mbannister@fastmail.fm
      link: mailto:mbannister@fastmail.fm
    - name: PGP public key
      link: assets/asc/public_key.asc
    - name: O'Connor Hall, Room 17
    - name: (408) 551-3592
profiles:
    - name: Google Scholar
      link: http://scholar.google.com/citations?user=vwc4KwwAAAAJ

description: >
    I am an Assistant Professor of Computer Science in the
    <a href="//scu.edu/mathcs">Department of Mathematics and Computer Science</a>
    at <a href="//www.scu.edu">Santa Clara University</a>.
    My research interests are in the design and analysis of geometric and graph
    algorithms, particularly algorithms for graph drawing and network visualization.
